import { Technology, Topic, ChecklistItem, Note, FileItem, MindMap, LearningSession, ActivityLogItem } from "@/types/database";

export const SAMPLE_USER_ID = "00000000-0000-0000-0000-000000000001";

export const INITIAL_TECHNOLOGIES: Technology[] = [
  {
    id: "tech-java",
    user_id: SAMPLE_USER_ID,
    name: "Java",
    slug: "java",
    description: "Robust, object-oriented programming language and enterprise runtime ecosystem.",
    icon: "Coffee",
    category: "Backend",
    color: "#e76f51",
    progress: 75,
    is_favorite: true,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "tech-spring-boot",
    user_id: SAMPLE_USER_ID,
    name: "Spring Boot",
    slug: "spring-boot",
    description: "Enterprise Java framework for building scalable microservices, REST APIs, and secure applications.",
    icon: "Leaf",
    category: "Backend",
    color: "#2a9d8f",
    progress: 80,
    is_favorite: true,
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "tech-docker",
    user_id: SAMPLE_USER_ID,
    name: "Docker",
    slug: "docker",
    description: "Platform for developing, shipping, and running applications in lightweight, isolated containers.",
    icon: "Container",
    category: "DevOps",
    color: "#0077b6",
    progress: 60,
    is_favorite: true,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "tech-postgresql",
    user_id: SAMPLE_USER_ID,
    name: "PostgreSQL",
    slug: "postgresql",
    description: "Powerful open-source relational database supporting advanced queries, JSONB, indexing, and ACID.",
    icon: "Database",
    category: "Database",
    color: "#336791",
    progress: 65,
    is_favorite: false,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "tech-react",
    user_id: SAMPLE_USER_ID,
    name: "React",
    slug: "react",
    description: "Declarative, component-based library for building responsive and modern web user interfaces.",
    icon: "Code2",
    category: "Frontend",
    color: "#61dafb",
    progress: 85,
    is_favorite: true,
    created_at: new Date(Date.now() - 18 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "tech-ai",
    user_id: SAMPLE_USER_ID,
    name: "Artificial Intelligence",
    slug: "artificial-intelligence",
    description: "Modern machine learning, LLM architectures, vector search, embeddings, and RAG pipelines.",
    icon: "Cpu",
    category: "AI & ML",
    color: "#9d4edd",
    progress: 40,
    is_favorite: true,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_TOPICS: Topic[] = [
  // --- JAVA HIERARCHY ---
  // Level 1: Core Java
  {
    id: "topic-java-core",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-java",
    parent_topic_id: null,
    name: "Core Java",
    slug: "core-java",
    description: "Fundamentals of Java syntax, data structures, and object-oriented principles.",
    status: "Completed",
    progress: 100,
    priority: "High",
    sort_order: 1,
    is_favorite: false,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    completed_at: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: "topic-java-variables",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-java",
    parent_topic_id: "topic-java-core",
    name: "Variables & Data Types",
    slug: "variables-and-data-types",
    description: "Primitives, wrapper classes, reference types, and type casting.",
    status: "Completed",
    progress: 100,
    priority: "Medium",
    sort_order: 1,
    is_favorite: false,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    completed_at: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: "topic-java-oop",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-java",
    parent_topic_id: "topic-java-core",
    name: "Object-Oriented Programming (OOP)",
    slug: "oop",
    description: "Inheritance, polymorphism, encapsulation, abstraction, and SOLID principles.",
    status: "Completed",
    progress: 100,
    priority: "High",
    sort_order: 2,
    is_favorite: true,
    created_at: new Date(Date.now() - 28 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    completed_at: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: "topic-java-collections",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-java",
    parent_topic_id: "topic-java-core",
    name: "Collections Framework",
    slug: "collections-framework",
    description: "List, Set, Map, Queue, HashMap internal mechanics, and Streams API.",
    status: "Completed",
    progress: 100,
    priority: "High",
    sort_order: 3,
    is_favorite: false,
    created_at: new Date(Date.now() - 26 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 18 * 86400000).toISOString(),
    completed_at: new Date(Date.now() - 18 * 86400000).toISOString(),
  },
  {
    id: "topic-java-exceptions",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-java",
    parent_topic_id: "topic-java-core",
    name: "Exception Handling",
    slug: "exception-handling",
    description: "Checked vs Unchecked exceptions, try-with-resources, custom exceptions.",
    status: "Completed",
    progress: 100,
    priority: "Medium",
    sort_order: 4,
    is_favorite: false,
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 16 * 86400000).toISOString(),
    completed_at: new Date(Date.now() - 16 * 86400000).toISOString(),
  },
  {
    id: "topic-java-generics",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-java",
    parent_topic_id: "topic-java-core",
    name: "Generics",
    slug: "generics",
    description: "Generic classes, methods, type wildcards <? extends T>, and type erasure.",
    status: "Completed",
    progress: 100,
    priority: "Medium",
    sort_order: 5,
    is_favorite: false,
    created_at: new Date(Date.now() - 24 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    completed_at: new Date(Date.now() - 15 * 86400000).toISOString(),
  },

  // Level 1: Multithreading
  {
    id: "topic-java-concurrency",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-java",
    parent_topic_id: null,
    name: "Multithreading & Concurrency",
    slug: "multithreading-and-concurrency",
    description: "Thread lifecycle, memory models, thread pools, locks, and synchronization.",
    status: "Learning",
    progress: 65,
    priority: "High",
    sort_order: 2,
    is_favorite: true,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    last_studied_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: "topic-java-threads",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-java",
    parent_topic_id: "topic-java-concurrency",
    name: "Threads & Runnable",
    slug: "threads-and-runnable",
    description: "Thread creation, states, daemon threads, and join/yield methods.",
    status: "Completed",
    progress: 100,
    priority: "High",
    sort_order: 1,
    is_favorite: false,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    completed_at: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
  {
    id: "topic-java-executors",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-java",
    parent_topic_id: "topic-java-concurrency",
    name: "Executors & Thread Pools",
    slug: "executors-and-thread-pools",
    description: "ThreadPoolExecutor, FixedThreadPool, CachedThreadPool, Callable & Future.",
    status: "Learning",
    progress: 70,
    priority: "High",
    sort_order: 2,
    is_favorite: false,
    created_at: new Date(Date.now() - 18 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    last_studied_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: "topic-java-sync",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-java",
    parent_topic_id: "topic-java-concurrency",
    name: "Synchronization & Volatile",
    slug: "synchronization-and-volatile",
    description: "Synchronized blocks, volatile keyword, race conditions, and deadlocks.",
    status: "Learning",
    progress: 60,
    priority: "High",
    sort_order: 3,
    is_favorite: false,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    last_studied_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: "topic-java-concurrent-coll",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-java",
    parent_topic_id: "topic-java-concurrency",
    name: "Concurrent Collections",
    slug: "concurrent-collections",
    description: "ConcurrentHashMap, CopyOnWriteArrayList, BlockingQueue.",
    status: "Not Started",
    progress: 20,
    priority: "Medium",
    sort_order: 4,
    is_favorite: false,
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  },

  // Level 1: JVM Internals
  {
    id: "topic-java-jvm",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-java",
    parent_topic_id: null,
    name: "JVM Architecture & Memory",
    slug: "jvm-architecture-and-memory",
    description: "Deep dive into memory zones, garbage collectors (G1, ZGC), and bytecode.",
    status: "Learning",
    progress: 55,
    priority: "High",
    sort_order: 3,
    is_favorite: false,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    last_studied_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: "topic-java-heap-stack",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-java",
    parent_topic_id: "topic-java-jvm",
    name: "Heap vs Stack Memory",
    slug: "heap-vs-stack-memory",
    description: "Eden space, Survivor spaces, Metaspace, and Stack frames.",
    status: "Completed",
    progress: 100,
    priority: "High",
    sort_order: 1,
    is_favorite: false,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    completed_at: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  {
    id: "topic-java-gc",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-java",
    parent_topic_id: "topic-java-jvm",
    name: "Garbage Collection Algorithms",
    slug: "garbage-collection-algorithms",
    description: "Mark-Sweep-Compact, Generational GC, G1 GC tuning, and ZGC.",
    status: "Learning",
    progress: 50,
    priority: "High",
    sort_order: 2,
    is_favorite: true,
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    last_studied_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  },

  // --- SPRING BOOT HIERARCHY ---
  {
    id: "topic-spring-security",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-spring-boot",
    parent_topic_id: null,
    name: "Spring Security",
    slug: "spring-security",
    description: "Authentication, authorization, security filter chains, and OAuth2.",
    status: "Learning",
    progress: 75,
    priority: "High",
    sort_order: 1,
    is_favorite: true,
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    last_studied_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: "topic-spring-jwt",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-spring-boot",
    parent_topic_id: "topic-spring-security",
    name: "JWT Authentication",
    slug: "jwt-authentication",
    description: "Stateless authentication flow using JSON Web Tokens with access and refresh tokens.",
    status: "Learning",
    progress: 65,
    priority: "High",
    sort_order: 1,
    is_favorite: true,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    last_studied_at: new Date().toISOString(),
  },
  {
    id: "topic-spring-jpa",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-spring-boot",
    parent_topic_id: null,
    name: "Spring Data JPA & Hibernate",
    slug: "spring-data-jpa-and-hibernate",
    description: "Entity lifecycle, repositories, JPQL queries, pagination, and N+1 problem.",
    status: "Completed",
    progress: 100,
    priority: "High",
    sort_order: 2,
    is_favorite: false,
    created_at: new Date(Date.now() - 22 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    completed_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },

  // --- DOCKER HIERARCHY ---
  {
    id: "topic-docker-basics",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-docker",
    parent_topic_id: null,
    name: "Containers & Images",
    slug: "containers-and-images",
    description: "Dockerfile directives, image layers, caching, and container lifecycle.",
    status: "Completed",
    progress: 100,
    priority: "High",
    sort_order: 1,
    is_favorite: false,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    completed_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: "topic-docker-compose",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-docker",
    parent_topic_id: null,
    name: "Docker Compose",
    slug: "docker-compose",
    description: "Multi-container orchestration, networks, volumes, healthchecks, and environment variables.",
    status: "Learning",
    progress: 40,
    priority: "Medium",
    sort_order: 2,
    is_favorite: true,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    last_studied_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },

  // --- AI & LLMs HIERARCHY ---
  {
    id: "topic-ai-llm-foundations",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-ai",
    parent_topic_id: null,
    name: "LLM Foundations & Transformers",
    slug: "llm-foundations-and-transformers",
    description: "Self-attention mechanism, transformer encoder-decoder, tokenization, and temperature.",
    status: "Completed",
    progress: 100,
    priority: "High",
    sort_order: 1,
    is_favorite: false,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    completed_at: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
  {
    id: "topic-ai-rag",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-ai",
    parent_topic_id: null,
    name: "Retrieval-Augmented Generation (RAG)",
    slug: "retrieval-augmented-generation",
    description: "Vector embeddings, cosine similarity, pgvector, hybrid search, and reranking.",
    status: "Learning",
    progress: 45,
    priority: "High",
    sort_order: 2,
    is_favorite: true,
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    last_studied_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
];

export const INITIAL_CHECKLIST_ITEMS: ChecklistItem[] = [
  // JWT Checklist Items
  {
    id: "chk-jwt-1",
    user_id: SAMPLE_USER_ID,
    topic_id: "topic-spring-jwt",
    title: "What is JWT and stateless authentication?",
    is_completed: true,
    sort_order: 1,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  {
    id: "chk-jwt-2",
    user_id: SAMPLE_USER_ID,
    topic_id: "topic-spring-jwt",
    title: "JWT structure: Header, Payload (Claims), Signature",
    is_completed: true,
    sort_order: 2,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: "chk-jwt-3",
    user_id: SAMPLE_USER_ID,
    topic_id: "topic-spring-jwt",
    title: "Claims: Standard claims (sub, exp, iat) vs Custom claims",
    is_completed: true,
    sort_order: 3,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: "chk-jwt-4",
    user_id: SAMPLE_USER_ID,
    topic_id: "topic-spring-jwt",
    title: "Signing algorithms: HMAC-SHA256 vs RSA public/private keys",
    is_completed: true,
    sort_order: 4,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: "chk-jwt-5",
    user_id: SAMPLE_USER_ID,
    topic_id: "topic-spring-jwt",
    title: "Short-lived Access Tokens (e.g. 15 mins expiry)",
    is_completed: false,
    sort_order: 5,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "chk-jwt-6",
    user_id: SAMPLE_USER_ID,
    topic_id: "topic-spring-jwt",
    title: "Secure Refresh Token rotation and database storage",
    is_completed: false,
    sort_order: 6,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "chk-jwt-7",
    user_id: SAMPLE_USER_ID,
    topic_id: "topic-spring-jwt",
    title: "Custom JwtAuthenticationFilter extending OncePerRequestFilter",
    is_completed: false,
    sort_order: 7,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Docker Compose Checklist
  {
    id: "chk-dc-1",
    user_id: SAMPLE_USER_ID,
    topic_id: "topic-docker-compose",
    title: "compose.yaml syntax and services block",
    is_completed: true,
    sort_order: 1,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: "chk-dc-2",
    user_id: SAMPLE_USER_ID,
    topic_id: "topic-docker-compose",
    title: "Custom bridge networks and DNS service resolution",
    is_completed: true,
    sort_order: 2,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: "chk-dc-3",
    user_id: SAMPLE_USER_ID,
    topic_id: "topic-docker-compose",
    title: "Named volumes for database persistence (Postgres/Redis)",
    is_completed: false,
    sort_order: 3,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "chk-dc-4",
    user_id: SAMPLE_USER_ID,
    topic_id: "topic-docker-compose",
    title: "Healthchecks and `depends_on: { condition: service_healthy }`",
    is_completed: false,
    sort_order: 4,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_NOTES: Note[] = [
  {
    id: "note-jwt-deepdive",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-spring-boot",
    topic_id: "topic-spring-jwt",
    title: "JWT Authentication Architecture & Filter Chain in Spring Security 6",
    tags: ["spring-security", "jwt", "auth", "backend"],
    is_favorite: true,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    content_html: `
      <h2>JWT Authentication Flow Overview</h2>
      <p>JSON Web Tokens (JWT) allow stateless authentication between a client (SPA or Mobile app) and the backend REST API without storing server-side session state.</p>
      
      <h3>1. The Three Parts of a JWT</h3>
      <ul>
        <li><strong>Header:</strong> Specifies token type (<code>JWT</code>) and hashing algorithm (e.g. <code>HS256</code> or <code>RS256</code>).</li>
        <li><strong>Payload (Claims):</strong> Contains claims such as subject (<code>sub</code>: username/userId), issuer (<code>iss</code>), issuedAt (<code>iat</code>), expiration (<code>exp</code>), and custom roles (<code>roles: ["ROLE_ADMIN"]</code>).</li>
        <li><strong>Signature:</strong> Generated by signing the encoded header and payload with a secret key or private key.</li>
      </ul>

      <h3>2. Key Java Implementation Snippet</h3>
      <pre><code class="language-java">@Component
public class JwtService {
    @Value("\${jwt.secret}")
    private String secretKey;

    public String generateToken(UserDetails userDetails) {
        return Jwts.builder()
            .setSubject(userDetails.getUsername())
            .setIssuedAt(new Date())
            .setExpiration(new Date(System.currentTimeMillis() + 1000 * 60 * 15)) // 15 mins
            .signWith(getSigningKey(), SignatureAlgorithm.HS256)
            .compact();
    }
}</code></pre>

      <h3>3. Security Best Practices</h3>
      <blockquote>
        <p>Always store Refresh Tokens in httpOnly, secure, SameSite=Strict cookies to protect against XSS attacks, while short-lived Access Tokens can remain in memory.</p>
      </blockquote>
    `,
  },
  {
    id: "note-docker-compose-setup",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-docker",
    topic_id: "topic-docker-compose",
    title: "Production-Ready Docker Compose for Fullstack App",
    tags: ["docker", "devops", "containers", "postgres"],
    is_favorite: true,
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    content_html: `
      <h2>Multi-Container Setup with Healthchecks</h2>
      <p>Using Docker Compose with inter-service networking and resilient database health checks.</p>
      <pre><code class="language-yaml">services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://user:pass@db:5432/mydb
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:</code></pre>
    `,
  },
  {
    id: "note-rag-pipeline",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-ai",
    topic_id: "topic-ai-rag",
    title: "Understanding Chunking & Vector Search in RAG Systems",
    tags: ["ai", "rag", "embeddings", "vector-db"],
    is_favorite: false,
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    content_html: `
      <h2>RAG Architecture Fundamentals</h2>
      <p>Retrieval-Augmented Generation bridges static LLM weights with dynamic domain knowledge.</p>
      <h3>Chunking Strategies:</h3>
      <ul>
        <li><strong>Fixed-size chunking:</strong> 500-1000 tokens with 10-20% overlap.</li>
        <li><strong>Semantic chunking:</strong> Splitting based on document headings and structural units.</li>
      </ul>
      <p>Cosine similarity formula: <code>cosine_similarity(A, B) = (A · B) / (||A|| * ||B||)</code></p>
    `,
  },
];

export const INITIAL_FILES: FileItem[] = [
  {
    id: "file-spring-pdf",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-spring-boot",
    topic_id: "topic-spring-jwt",
    filename: "Spring_Security_6_Architecture_Guide.pdf",
    file_type: "application/pdf",
    file_size: 2458000,
    storage_path: "documents/Spring_Security_6_Architecture_Guide.pdf",
    public_url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=1200&auto=format&fit=crop&q=80",
    is_handwritten: false,
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
  {
    id: "file-jwt-handwritten",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-spring-boot",
    topic_id: "topic-spring-jwt",
    filename: "JWT_Filter_Chain_Handwritten_Diagram.jpg",
    file_type: "image/jpeg",
    file_size: 1845000,
    storage_path: "handwritten/JWT_Filter_Chain_Handwritten_Diagram.jpg",
    public_url: "https://images.unsplash.com/photo-1517842645767-c639042777db?w=1200&auto=format&fit=crop&q=80",
    is_handwritten: true,
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
  {
    id: "file-docker-pdf",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-docker",
    topic_id: "topic-docker-compose",
    filename: "Docker_Compose_Cheat_Sheet.pdf",
    file_type: "application/pdf",
    file_size: 1120000,
    storage_path: "documents/Docker_Compose_Cheat_Sheet.pdf",
    public_url: "https://images.unsplash.com/photo-1607799279861-4dd421887fb3?w=1200&auto=format&fit=crop&q=80",
    is_handwritten: false,
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: "file-jvm-notes-scan",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-java",
    topic_id: "topic-java-gc",
    filename: "JVM_Memory_Generations_Sketches.png",
    file_type: "image/png",
    file_size: 3200000,
    storage_path: "handwritten/JVM_Memory_Generations_Sketches.png",
    public_url: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=1200&auto=format&fit=crop&q=80",
    is_handwritten: true,
    created_at: new Date(Date.now() - 9 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 9 * 86400000).toISOString(),
  },
];

export const INITIAL_MIND_MAPS: MindMap[] = [
  {
    id: "map-spring-security",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-spring-boot",
    topic_id: "topic-spring-jwt",
    title: "Spring Security & JWT Authentication Ecosystem",
    description: "Hierarchical visual breakdown of authentication filters, token structures, and authorization interceptors.",
    is_favorite: true,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    nodes_json: [
      {
        id: "node-root",
        type: "custom",
        position: { x: 350, y: 50 },
        data: { label: "Spring Security", isRoot: true, color: "#2a9d8f", description: "Security Core Engine" },
      },
      {
        id: "node-auth",
        type: "custom",
        position: { x: 100, y: 180 },
        data: { label: "Authentication", color: "#3b82f6", description: "Who are you?" },
      },
      {
        id: "node-authz",
        type: "custom",
        position: { x: 350, y: 180 },
        data: { label: "Authorization", color: "#8b5cf6", description: "What can you do?" },
      },
      {
        id: "node-jwt",
        type: "custom",
        position: { x: 600, y: 180 },
        data: { label: "JWT Tokens", color: "#ec4899", description: "Stateless Bearer Tokens" },
      },
      {
        id: "node-user-pass",
        type: "custom",
        position: { x: 20, y: 310 },
        data: { label: "Username / Password", color: "#0ea5e9", description: "DaoAuthenticationProvider" },
      },
      {
        id: "node-oauth2",
        type: "custom",
        position: { x: 180, y: 310 },
        data: { label: "OAuth2 / OIDC", color: "#06b6d4", description: "Google / GitHub Login" },
      },
      {
        id: "node-rbac",
        type: "custom",
        position: { x: 350, y: 310 },
        data: { label: "Role-Based (RBAC)", color: "#a855f7", description: "@PreAuthorize & Authorities" },
      },
      {
        id: "node-access-token",
        type: "custom",
        position: { x: 520, y: 310 },
        data: { label: "Access Token (15m)", color: "#f43f5e", description: "Short lived, memory only" },
      },
      {
        id: "node-refresh-token",
        type: "custom",
        position: { x: 680, y: 310 },
        data: { label: "Refresh Token (7d)", color: "#e11d48", description: "Stored in httpOnly Cookie" },
      },
    ],
    edges_json: [
      { id: "e1", source: "node-root", target: "node-auth", animated: true },
      { id: "e2", source: "node-root", target: "node-authz", animated: true },
      { id: "e3", source: "node-root", target: "node-jwt", animated: true },
      { id: "e4", source: "node-auth", target: "node-user-pass" },
      { id: "e5", source: "node-auth", target: "node-oauth2" },
      { id: "e6", source: "node-authz", target: "node-rbac" },
      { id: "e7", source: "node-jwt", target: "node-access-token" },
      { id: "e8", source: "node-jwt", target: "node-refresh-token" },
    ],
  },
  {
    id: "map-docker-arch",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-docker",
    topic_id: "topic-docker-compose",
    title: "Docker Architecture & Multi-Stage Pipeline",
    description: "Visual relationship map between Docker daemon, images, container networks, and volumes.",
    is_favorite: false,
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    nodes_json: [
      {
        id: "node-docker-root",
        type: "custom",
        position: { x: 350, y: 50 },
        data: { label: "Docker Engine", isRoot: true, color: "#0077b6", description: "Host Container Runtime" },
      },
      {
        id: "node-images",
        type: "custom",
        position: { x: 120, y: 180 },
        data: { label: "Images & Dockerfiles", color: "#0284c7", description: "Layered Read-Only Filesystems" },
      },
      {
        id: "node-containers",
        type: "custom",
        position: { x: 350, y: 180 },
        data: { label: "Active Containers", color: "#059669", description: "Isolated Namespaces & Cgroups" },
      },
      {
        id: "node-storage",
        type: "custom",
        position: { x: 580, y: 180 },
        data: { label: "Storage & Networks", color: "#d97706", description: "Named Volumes & Bridges" },
      },
    ],
    edges_json: [
      { id: "e-d1", source: "node-docker-root", target: "node-images", animated: true },
      { id: "e-d2", source: "node-docker-root", target: "node-containers", animated: true },
      { id: "e-d3", source: "node-docker-root", target: "node-storage", animated: true },
    ],
  },
];

// Generate 30 days of learning sessions for realistic charts & GitHub heatmap
export const INITIAL_LEARNING_SESSIONS: LearningSession[] = [
  {
    id: "sess-1",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-spring-boot",
    topic_id: "topic-spring-jwt",
    date: new Date().toISOString().split("T")[0],
    duration_minutes: 90,
    title: "Studied JWT Authentication & Filter Chain",
    description: "Configured OncePerRequestFilter and extracted Bearer token from authorization headers.",
    created_at: new Date().toISOString(),
  },
  {
    id: "sess-2",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-spring-boot",
    topic_id: "topic-spring-jwt",
    date: new Date(Date.now() - 1 * 86400000).toISOString().split("T")[0],
    duration_minutes: 60,
    title: "Claims & Token Expiration Handling",
    description: "Tested expired token rejection and custom unauthorized entry point responses.",
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: "sess-3",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-java",
    topic_id: "topic-java-sync",
    date: new Date(Date.now() - 2 * 86400000).toISOString().split("T")[0],
    duration_minutes: 75,
    title: "Java Synchronization & Volatile keyword",
    description: "Deep dive into happens-before relationships and atomic references.",
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: "sess-4",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-docker",
    topic_id: "topic-docker-compose",
    date: new Date(Date.now() - 3 * 86400000).toISOString().split("T")[0],
    duration_minutes: 120,
    title: "Docker Compose networking & Postgres healthchecks",
    description: "Setup multi-service configuration with dependent start orders.",
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: "sess-5",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-java",
    topic_id: "topic-java-gc",
    date: new Date(Date.now() - 4 * 86400000).toISOString().split("T")[0],
    duration_minutes: 45,
    title: "JVM Garbage Collection Analysis",
    description: "Explored G1 GC generational pauses and memory pool allocation in JConsole.",
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: "sess-6",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-react",
    topic_id: null,
    date: new Date(Date.now() - 5 * 86400000).toISOString().split("T")[0],
    duration_minutes: 110,
    title: "React Server Components & Streaming SSR",
    description: "Studied async server components and Suspense boundaries.",
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: "sess-7",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-ai",
    topic_id: "topic-ai-rag",
    date: new Date(Date.now() - 6 * 86400000).toISOString().split("T")[0],
    duration_minutes: 80,
    title: "Vector Embeddings & pgvector in Postgres",
    description: "Implemented HNSW indexing and similarity search with dot product.",
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
  {
    id: "sess-8",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-postgresql",
    topic_id: null,
    date: new Date(Date.now() - 8 * 86400000).toISOString().split("T")[0],
    duration_minutes: 90,
    title: "PostgreSQL Index Optimization with EXPLAIN ANALYZE",
    description: "Compared sequential scans against B-Tree index scans with composite filters.",
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  {
    id: "sess-9",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-java",
    topic_id: "topic-java-executors",
    date: new Date(Date.now() - 10 * 86400000).toISOString().split("T")[0],
    duration_minutes: 105,
    title: "ThreadPoolExecutor tuning & queue limits",
    description: "Configured core vs max pool size and caller-runs rejection policies.",
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: "sess-10",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-spring-boot",
    topic_id: "topic-spring-jpa",
    date: new Date(Date.now() - 12 * 86400000).toISOString().split("T")[0],
    duration_minutes: 60,
    title: "Resolving JPA N+1 with EntityGraphs",
    description: "Benchmarked JOIN FETCH queries vs @EntityGraph annotations.",
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
  {
    id: "sess-11",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-ai",
    topic_id: "topic-ai-llm-foundations",
    date: new Date(Date.now() - 15 * 86400000).toISOString().split("T")[0],
    duration_minutes: 120,
    title: "Transformer Attention Heads & Math",
    description: "Calculated Query, Key, Value matrix multiplication by hand.",
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: "sess-12",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-java",
    topic_id: "topic-java-oop",
    date: new Date(Date.now() - 18 * 86400000).toISOString().split("T")[0],
    duration_minutes: 90,
    title: "SOLID Principles in Clean Architecture",
    description: "Refactored tightly coupled modules using dependency inversion.",
    created_at: new Date(Date.now() - 18 * 86400000).toISOString(),
  },
  {
    id: "sess-13",
    user_id: SAMPLE_USER_ID,
    technology_id: "tech-docker",
    topic_id: "topic-docker-basics",
    date: new Date(Date.now() - 20 * 86400000).toISOString().split("T")[0],
    duration_minutes: 60,
    title: "Multi-stage Docker builds for small Alpine images",
    description: "Reduced final image size from 850MB to 140MB using JRE alpine base.",
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
];

export const INITIAL_ACTIVITY_LOG: ActivityLogItem[] = [
  {
    id: "act-1",
    user_id: SAMPLE_USER_ID,
    entity_type: "topic",
    entity_id: "topic-spring-jwt",
    action_type: "updated",
    title: "Updated progress for JWT Authentication to 65%",
    created_at: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    id: "act-2",
    user_id: SAMPLE_USER_ID,
    entity_type: "note",
    entity_id: "note-jwt-deepdive",
    action_type: "created",
    title: "Added note 'JWT Authentication Architecture & Filter Chain'",
    created_at: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: "act-3",
    user_id: SAMPLE_USER_ID,
    entity_type: "session",
    entity_id: "sess-1",
    action_type: "created",
    title: "Logged 1h 30m study session on Spring Security",
    created_at: new Date(Date.now() - 4 * 3600000).toISOString(),
  },
  {
    id: "act-4",
    user_id: SAMPLE_USER_ID,
    entity_type: "file",
    entity_id: "file-jwt-handwritten",
    action_type: "uploaded",
    title: "Uploaded handwritten note 'JWT_Filter_Chain_Handwritten_Diagram.jpg'",
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: "act-5",
    user_id: SAMPLE_USER_ID,
    entity_type: "mind_map",
    entity_id: "map-spring-security",
    action_type: "updated",
    title: "Updated mind map 'Spring Security & JWT Authentication Ecosystem'",
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: "act-6",
    user_id: SAMPLE_USER_ID,
    entity_type: "topic",
    entity_id: "topic-java-heap-stack",
    action_type: "completed",
    title: "Completed topic 'Heap vs Stack Memory'",
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  {
    id: "act-7",
    user_id: SAMPLE_USER_ID,
    entity_type: "technology",
    entity_id: "tech-ai",
    action_type: "created",
    title: "Added new technology 'Artificial Intelligence'",
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
];
